### ISSUE TITLE
koordynaty

### ISSUE THREAD

**Issue by k3chupe** [DamianRyczko/PlanetColonyAgentSimulation#1]
Wydaje mi się, że powinniśmy zrobić jedna zmienna, która ma w sobie x i y, a nie osobno dwie.

**Comment by DamianRyczko** [comment]
> , a n

ale w któym miejscu w klasie budnki czy w miejscu gdzie wyszukuje najbliższe złoże. Jaki ma to wpływ na kod jak żaden to nie warto tu dobrze widać i tak ze coś ma współrzędne x i y
